package identity

import (
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

type URLVerifier struct {
	Client *http.Client
}

func NewURLVerifier() *URLVerifier {
	return &URLVerifier{
		Client: &http.Client{
			Timeout: 10 * time.Second,
		},
	}
}

// Verify checks a custom URL for a JSON response containing a signed message.
// The JSON must contain a 'message' and a 'signature' (hex-encoded).
// It verifies that the signature was generated by the provided publicKeyHex.
func (v *URLVerifier) Verify(url string, expectedMessage string, publicKeyHex string) (bool, error) {
	if !strings.HasPrefix(url, "https://") && !strings.HasPrefix(url, "http://") {
		return false, fmt.Errorf("invalid URL scheme, must be http or https")
	}

	pubKeyBytes, err := hex.DecodeString(publicKeyHex)
	if err != nil {
		return false, fmt.Errorf("invalid public key hex: %w", err)
	}

	if len(pubKeyBytes) != ed25519.PublicKeySize {
		return false, fmt.Errorf("invalid public key size, expected %d bytes", ed25519.PublicKeySize)
	}
	pubKey := ed25519.PublicKey(pubKeyBytes)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return false, fmt.Errorf("failed to create request: %w", err)
	}
	req.Header.Set("Accept", "application/json")

	resp, err := v.Client.Do(req)
	if err != nil {
		return false, fmt.Errorf("failed to fetch URL: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return false, fmt.Errorf("unexpected status code: %d", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return false, fmt.Errorf("failed to read response: %w", err)
	}

	var payload struct {
		Message   string `json:"message"`
		Signature string `json:"signature"` // hex encoded
	}

	if err := json.Unmarshal(body, &payload); err != nil {
		return false, fmt.Errorf("failed to parse JSON response: %w", err)
	}

	if payload.Message != expectedMessage {
		return false, fmt.Errorf("message mismatch: expected %q, got %q", expectedMessage, payload.Message)
	}

	sigBytes, err := hex.DecodeString(payload.Signature)
	if err != nil {
		return false, fmt.Errorf("invalid signature hex: %w", err)
	}

	if len(sigBytes) != ed25519.SignatureSize {
		return false, fmt.Errorf("invalid signature size, expected %d bytes", ed25519.SignatureSize)
	}

	isValid := ed25519.Verify(pubKey, []byte(payload.Message), sigBytes)
	return isValid, nil
}
